name: food_recognition_app
description: Приложение для распознавания ингредиентов и получения рецептов.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.0
  path_provider: ^2.0.11
  path: ^1.8.2
  http: ^1.1.0
  cupertino_icons: ^1.0.5
  image_picker: ^0.8.7

  # Firebase зависимости
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4

  # Google аутентификация
  google_sign_in: ^6.1.4

  # Управление состоянием
  provider: ^6.0.5

  # Полезные утилиты
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
